// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/metrics/v1/messages.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetricsRequest) Reset() {
	*x = UploadMetricsRequest{}
	mi := &file_api_metrics_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricsRequest) ProtoMessage() {}

func (x *UploadMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricsRequest.ProtoReflect.Descriptor instead.
func (*UploadMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_metrics_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMetricsRequest) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UploadMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           float64                `protobuf:"fixed64,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Average       float64                `protobuf:"fixed64,2,opt,name=average,proto3" json:"average,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetricsResponse) Reset() {
	*x = UploadMetricsResponse{}
	mi := &file_api_metrics_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetricsResponse) ProtoMessage() {}

func (x *UploadMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_metrics_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetricsResponse.ProtoReflect.Descriptor instead.
func (*UploadMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_metrics_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMetricsResponse) GetSum() float64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *UploadMetricsResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *UploadMetricsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_metrics_v1_messages_proto protoreflect.FileDescriptor

const file_api_metrics_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/metrics/v1/messages.proto\x12\x0eapi.metrics.v1\",\n" +
	"\x14UploadMetricsRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\"Y\n" +
	"\x15UploadMetricsResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x01R\x03sum\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x01R\aaverage\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05countB4Z2github.com/Egorpalan/grpc-easyp/pkg/api/metrics/v1b\x06proto3"

var (
	file_api_metrics_v1_messages_proto_rawDescOnce sync.Once
	file_api_metrics_v1_messages_proto_rawDescData []byte
)

func file_api_metrics_v1_messages_proto_rawDescGZIP() []byte {
	file_api_metrics_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_metrics_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_metrics_v1_messages_proto_rawDesc), len(file_api_metrics_v1_messages_proto_rawDesc)))
	})
	return file_api_metrics_v1_messages_proto_rawDescData
}

var file_api_metrics_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_metrics_v1_messages_proto_goTypes = []any{
	(*UploadMetricsRequest)(nil),  // 0: api.metrics.v1.UploadMetricsRequest
	(*UploadMetricsResponse)(nil), // 1: api.metrics.v1.UploadMetricsResponse
}
var file_api_metrics_v1_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_metrics_v1_messages_proto_init() }
func file_api_metrics_v1_messages_proto_init() {
	if File_api_metrics_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_metrics_v1_messages_proto_rawDesc), len(file_api_metrics_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_metrics_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_metrics_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_metrics_v1_messages_proto_msgTypes,
	}.Build()
	File_api_metrics_v1_messages_proto = out.File
	file_api_metrics_v1_messages_proto_goTypes = nil
	file_api_metrics_v1_messages_proto_depIdxs = nil
}
