// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/metrics/v1/metrics.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsAPI_UploadMetrics_FullMethodName = "/api.metrics.v1.MetricsAPI/UploadMetrics"
)

// MetricsAPIClient is the client API for MetricsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetricsAPIClient interface {
	UploadMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadMetricsRequest, UploadMetricsResponse], error)
}

type metricsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsAPIClient(cc grpc.ClientConnInterface) MetricsAPIClient {
	return &metricsAPIClient{cc}
}

func (c *metricsAPIClient) UploadMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadMetricsRequest, UploadMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricsAPI_ServiceDesc.Streams[0], MetricsAPI_UploadMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadMetricsRequest, UploadMetricsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsAPI_UploadMetricsClient = grpc.ClientStreamingClient[UploadMetricsRequest, UploadMetricsResponse]

// MetricsAPIServer is the server API for MetricsAPI service.
// All implementations should embed UnimplementedMetricsAPIServer
// for forward compatibility.
type MetricsAPIServer interface {
	UploadMetrics(grpc.ClientStreamingServer[UploadMetricsRequest, UploadMetricsResponse]) error
}

// UnimplementedMetricsAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsAPIServer struct{}

func (UnimplementedMetricsAPIServer) UploadMetrics(grpc.ClientStreamingServer[UploadMetricsRequest, UploadMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadMetrics not implemented")
}
func (UnimplementedMetricsAPIServer) testEmbeddedByValue() {}

// UnsafeMetricsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsAPIServer will
// result in compilation errors.
type UnsafeMetricsAPIServer interface {
	mustEmbedUnimplementedMetricsAPIServer()
}

func RegisterMetricsAPIServer(s grpc.ServiceRegistrar, srv MetricsAPIServer) {
	// If the following call panics, it indicates UnimplementedMetricsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsAPI_ServiceDesc, srv)
}

func _MetricsAPI_UploadMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricsAPIServer).UploadMetrics(&grpc.GenericServerStream[UploadMetricsRequest, UploadMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricsAPI_UploadMetricsServer = grpc.ClientStreamingServer[UploadMetricsRequest, UploadMetricsResponse]

// MetricsAPI_ServiceDesc is the grpc.ServiceDesc for MetricsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.metrics.v1.MetricsAPI",
	HandlerType: (*MetricsAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadMetrics",
			Handler:       _MetricsAPI_UploadMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/metrics/v1/metrics.proto",
}
