// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/events/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_events_v1_events_proto protoreflect.FileDescriptor

const file_api_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/events/v1/events.proto\x12\rapi.events.v1\x1a\x1capi/events/v1/messages.proto2k\n" +
	"\tEventsAPI\x12^\n" +
	"\x11SubscribeToEvents\x12'.api.events.v1.SubscribeToEventsRequest\x1a\x1c.api.events.v1.EventResponse\"\x000\x01B3Z1github.com/Egorpalan/grpc-easyp/pkg/api/events/v1b\x06proto3"

var file_api_events_v1_events_proto_goTypes = []any{
	(*SubscribeToEventsRequest)(nil), // 0: api.events.v1.SubscribeToEventsRequest
	(*EventResponse)(nil),            // 1: api.events.v1.EventResponse
}
var file_api_events_v1_events_proto_depIdxs = []int32{
	0, // 0: api.events.v1.EventsAPI.SubscribeToEvents:input_type -> api.events.v1.SubscribeToEventsRequest
	1, // 1: api.events.v1.EventsAPI.SubscribeToEvents:output_type -> api.events.v1.EventResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_events_v1_events_proto_init() }
func file_api_events_v1_events_proto_init() {
	if File_api_events_v1_events_proto != nil {
		return
	}
	file_api_events_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_events_v1_events_proto_rawDesc), len(file_api_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_events_v1_events_proto_goTypes,
		DependencyIndexes: file_api_events_v1_events_proto_depIdxs,
	}.Build()
	File_api_events_v1_events_proto = out.File
	file_api_events_v1_events_proto_goTypes = nil
	file_api_events_v1_events_proto_depIdxs = nil
}
