// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/events/v1/events.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventsAPI_SubscribeToEvents_FullMethodName = "/api.events.v1.EventsAPI/SubscribeToEvents"
)

// EventsAPIClient is the client API for EventsAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventsAPIClient interface {
	SubscribeToEvents(ctx context.Context, in *SubscribeToEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error)
}

type eventsAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsAPIClient(cc grpc.ClientConnInterface) EventsAPIClient {
	return &eventsAPIClient{cc}
}

func (c *eventsAPIClient) SubscribeToEvents(ctx context.Context, in *SubscribeToEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventsAPI_ServiceDesc.Streams[0], EventsAPI_SubscribeToEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToEventsRequest, EventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventsAPI_SubscribeToEventsClient = grpc.ServerStreamingClient[EventResponse]

// EventsAPIServer is the server API for EventsAPI service.
// All implementations should embed UnimplementedEventsAPIServer
// for forward compatibility.
type EventsAPIServer interface {
	SubscribeToEvents(*SubscribeToEventsRequest, grpc.ServerStreamingServer[EventResponse]) error
}

// UnimplementedEventsAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventsAPIServer struct{}

func (UnimplementedEventsAPIServer) SubscribeToEvents(*SubscribeToEventsRequest, grpc.ServerStreamingServer[EventResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToEvents not implemented")
}
func (UnimplementedEventsAPIServer) testEmbeddedByValue() {}

// UnsafeEventsAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsAPIServer will
// result in compilation errors.
type UnsafeEventsAPIServer interface {
	mustEmbedUnimplementedEventsAPIServer()
}

func RegisterEventsAPIServer(s grpc.ServiceRegistrar, srv EventsAPIServer) {
	// If the following call panics, it indicates UnimplementedEventsAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventsAPI_ServiceDesc, srv)
}

func _EventsAPI_SubscribeToEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventsAPIServer).SubscribeToEvents(m, &grpc.GenericServerStream[SubscribeToEventsRequest, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventsAPI_SubscribeToEventsServer = grpc.ServerStreamingServer[EventResponse]

// EventsAPI_ServiceDesc is the grpc.ServiceDesc for EventsAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventsAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.events.v1.EventsAPI",
	HandlerType: (*EventsAPIServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToEvents",
			Handler:       _EventsAPI_SubscribeToEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/events/v1/events.proto",
}
