// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/events/v1/messages.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeToEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToEventsRequest) Reset() {
	*x = SubscribeToEventsRequest{}
	mi := &file_api_events_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToEventsRequest) ProtoMessage() {}

func (x *SubscribeToEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToEventsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_events_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeToEventsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type EventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventResponse_HealthCheck
	//	*EventResponse_NoteCreated
	Event         isEventResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_api_events_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_api_events_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *EventResponse) GetEvent() isEventResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventResponse) GetHealthCheck() *HealthCheck {
	if x != nil {
		if x, ok := x.Event.(*EventResponse_HealthCheck); ok {
			return x.HealthCheck
		}
	}
	return nil
}

func (x *EventResponse) GetNoteCreated() *NoteCreated {
	if x != nil {
		if x, ok := x.Event.(*EventResponse_NoteCreated); ok {
			return x.NoteCreated
		}
	}
	return nil
}

type isEventResponse_Event interface {
	isEventResponse_Event()
}

type EventResponse_HealthCheck struct {
	HealthCheck *HealthCheck `protobuf:"bytes,1,opt,name=health_check,json=healthCheck,proto3,oneof"`
}

type EventResponse_NoteCreated struct {
	NoteCreated *NoteCreated `protobuf:"bytes,2,opt,name=note_created,json=noteCreated,proto3,oneof"`
}

func (*EventResponse_HealthCheck) isEventResponse_Event() {}

func (*EventResponse_NoteCreated) isEventResponse_Event() {}

type HealthCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_api_events_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_api_events_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NoteCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteCreated) Reset() {
	*x = NoteCreated{}
	mi := &file_api_events_v1_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteCreated) ProtoMessage() {}

func (x *NoteCreated) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_v1_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteCreated.ProtoReflect.Descriptor instead.
func (*NoteCreated) Descriptor() ([]byte, []int) {
	return file_api_events_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *NoteCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_events_v1_messages_proto protoreflect.FileDescriptor

const file_api_events_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1capi/events/v1/messages.proto\x12\rapi.events.v1\x1a\x1bbuf/validate/validate.proto\"D\n" +
	"\x18SubscribeToEventsRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"\x9a\x01\n" +
	"\rEventResponse\x12?\n" +
	"\fhealth_check\x18\x01 \x01(\v2\x1a.api.events.v1.HealthCheckH\x00R\vhealthCheck\x12?\n" +
	"\fnote_created\x18\x02 \x01(\v2\x1a.api.events.v1.NoteCreatedH\x00R\vnoteCreatedB\a\n" +
	"\x05event\"'\n" +
	"\vHealthCheck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\vNoteCreated\x12\x17\n" +
	"\x02id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x02idB3Z1github.com/Egorpalan/grpc-easyp/pkg/api/events/v1b\x06proto3"

var (
	file_api_events_v1_messages_proto_rawDescOnce sync.Once
	file_api_events_v1_messages_proto_rawDescData []byte
)

func file_api_events_v1_messages_proto_rawDescGZIP() []byte {
	file_api_events_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_events_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_events_v1_messages_proto_rawDesc), len(file_api_events_v1_messages_proto_rawDesc)))
	})
	return file_api_events_v1_messages_proto_rawDescData
}

var file_api_events_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_events_v1_messages_proto_goTypes = []any{
	(*SubscribeToEventsRequest)(nil), // 0: api.events.v1.SubscribeToEventsRequest
	(*EventResponse)(nil),            // 1: api.events.v1.EventResponse
	(*HealthCheck)(nil),              // 2: api.events.v1.HealthCheck
	(*NoteCreated)(nil),              // 3: api.events.v1.NoteCreated
}
var file_api_events_v1_messages_proto_depIdxs = []int32{
	2, // 0: api.events.v1.EventResponse.health_check:type_name -> api.events.v1.HealthCheck
	3, // 1: api.events.v1.EventResponse.note_created:type_name -> api.events.v1.NoteCreated
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_events_v1_messages_proto_init() }
func file_api_events_v1_messages_proto_init() {
	if File_api_events_v1_messages_proto != nil {
		return
	}
	file_api_events_v1_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_events_v1_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*EventResponse_HealthCheck)(nil),
		(*EventResponse_NoteCreated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_events_v1_messages_proto_rawDesc), len(file_api_events_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_events_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_events_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_events_v1_messages_proto_msgTypes,
	}.Build()
	File_api_events_v1_messages_proto = out.File
	file_api_events_v1_messages_proto_goTypes = nil
	file_api_events_v1_messages_proto_depIdxs = nil
}
