// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/chat/v1/chat.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_chat_v1_chat_proto protoreflect.FileDescriptor

const file_api_chat_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x16api/chat/v1/chat.proto\x12\vapi.chat.v1\x1a\x1aapi/chat/v1/messages.proto2K\n" +
	"\aChatAPI\x12@\n" +
	"\x04Chat\x12\x18.api.chat.v1.ChatMessage\x1a\x18.api.chat.v1.ChatMessage\"\x00(\x010\x01B1Z/github.com/Egorpalan/grpc-easyp/pkg/api/chat/v1b\x06proto3"

var file_api_chat_v1_chat_proto_goTypes = []any{
	(*ChatMessage)(nil), // 0: api.chat.v1.ChatMessage
}
var file_api_chat_v1_chat_proto_depIdxs = []int32{
	0, // 0: api.chat.v1.ChatAPI.Chat:input_type -> api.chat.v1.ChatMessage
	0, // 1: api.chat.v1.ChatAPI.Chat:output_type -> api.chat.v1.ChatMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_chat_v1_chat_proto_init() }
func file_api_chat_v1_chat_proto_init() {
	if File_api_chat_v1_chat_proto != nil {
		return
	}
	file_api_chat_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_chat_proto_rawDesc), len(file_api_chat_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_v1_chat_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_chat_proto_depIdxs,
	}.Build()
	File_api_chat_v1_chat_proto = out.File
	file_api_chat_v1_chat_proto_goTypes = nil
	file_api_chat_v1_chat_proto_depIdxs = nil
}
