// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/chat/v1/messages.proto

package v1

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ChatMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ChatMessage_Message
	//	*ChatMessage_Error
	Content       isChatMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_chat_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_chat_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetContent() isChatMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ChatMessage) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Content.(*ChatMessage_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ChatMessage) GetError() *status.Status {
	if x != nil {
		if x, ok := x.Content.(*ChatMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isChatMessage_Content interface {
	isChatMessage_Content()
}

type ChatMessage_Message struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ChatMessage_Error struct {
	Error *status.Status `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ChatMessage_Message) isChatMessage_Content() {}

func (*ChatMessage_Error) isChatMessage_Content() {}

var File_api_chat_v1_messages_proto protoreflect.FileDescriptor

const file_api_chat_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/chat/v1/messages.proto\x12\vapi.chat.v1\x1a\x17google/rpc/status.proto\"b\n" +
	"\aMessage\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"v\n" +
	"\vChatMessage\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x14.api.chat.v1.MessageH\x00R\amessage\x12*\n" +
	"\x05error\x18\x02 \x01(\v2\x12.google.rpc.StatusH\x00R\x05errorB\t\n" +
	"\acontentB1Z/github.com/Egorpalan/grpc-easyp/pkg/api/chat/v1b\x06proto3"

var (
	file_api_chat_v1_messages_proto_rawDescOnce sync.Once
	file_api_chat_v1_messages_proto_rawDescData []byte
)

func file_api_chat_v1_messages_proto_rawDescGZIP() []byte {
	file_api_chat_v1_messages_proto_rawDescOnce.Do(func() {
		file_api_chat_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_v1_messages_proto_rawDesc), len(file_api_chat_v1_messages_proto_rawDesc)))
	})
	return file_api_chat_v1_messages_proto_rawDescData
}

var file_api_chat_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_chat_v1_messages_proto_goTypes = []any{
	(*Message)(nil),       // 0: api.chat.v1.Message
	(*ChatMessage)(nil),   // 1: api.chat.v1.ChatMessage
	(*status.Status)(nil), // 2: google.rpc.Status
}
var file_api_chat_v1_messages_proto_depIdxs = []int32{
	0, // 0: api.chat.v1.ChatMessage.message:type_name -> api.chat.v1.Message
	2, // 1: api.chat.v1.ChatMessage.error:type_name -> google.rpc.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_chat_v1_messages_proto_init() }
func file_api_chat_v1_messages_proto_init() {
	if File_api_chat_v1_messages_proto != nil {
		return
	}
	file_api_chat_v1_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*ChatMessage_Message)(nil),
		(*ChatMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_v1_messages_proto_rawDesc), len(file_api_chat_v1_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_chat_v1_messages_proto_goTypes,
		DependencyIndexes: file_api_chat_v1_messages_proto_depIdxs,
		MessageInfos:      file_api_chat_v1_messages_proto_msgTypes,
	}.Build()
	File_api_chat_v1_messages_proto = out.File
	file_api_chat_v1_messages_proto_goTypes = nil
	file_api_chat_v1_messages_proto_depIdxs = nil
}
