// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/notes/v1/errors.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED    ErrorCode = 0
	ErrorCode_ERROR_CODE_NOTE_NOT_FOUND ErrorCode = 1
	ErrorCode_ERROR_CODE_INVALID_INPUT  ErrorCode = 2
	ErrorCode_ERROR_CODE_INVALID_TEXT   ErrorCode = 3
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_NOTE_NOT_FOUND",
		2: "ERROR_CODE_INVALID_INPUT",
		3: "ERROR_CODE_INVALID_TEXT",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":    0,
		"ERROR_CODE_NOTE_NOT_FOUND": 1,
		"ERROR_CODE_INVALID_INPUT":  2,
		"ERROR_CODE_INVALID_TEXT":   3,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_notes_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_notes_v1_errors_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_notes_v1_errors_proto_rawDescGZIP(), []int{0}
}

type CustomError struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=api.notes.v1.ErrorCode" json:"code,omitempty"`
	Reason            string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	InternalErrorCode string                 `protobuf:"bytes,3,opt,name=internal_error_code,json=internalErrorCode,proto3" json:"internal_error_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CustomError) Reset() {
	*x = CustomError{}
	mi := &file_api_notes_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomError) ProtoMessage() {}

func (x *CustomError) ProtoReflect() protoreflect.Message {
	mi := &file_api_notes_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomError.ProtoReflect.Descriptor instead.
func (*CustomError) Descriptor() ([]byte, []int) {
	return file_api_notes_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *CustomError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *CustomError) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CustomError) GetInternalErrorCode() string {
	if x != nil {
		return x.InternalErrorCode
	}
	return ""
}

var File_api_notes_v1_errors_proto protoreflect.FileDescriptor

const file_api_notes_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x19api/notes/v1/errors.proto\x12\fapi.notes.v1\"\x82\x01\n" +
	"\vCustomError\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.api.notes.v1.ErrorCodeR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12.\n" +
	"\x13internal_error_code\x18\x03 \x01(\tR\x11internalErrorCode*\x81\x01\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ERROR_CODE_NOTE_NOT_FOUND\x10\x01\x12\x1c\n" +
	"\x18ERROR_CODE_INVALID_INPUT\x10\x02\x12\x1b\n" +
	"\x17ERROR_CODE_INVALID_TEXT\x10\x03B2Z0github.com/Egorpalan/grpc-easyp/pkg/api/notes/v1b\x06proto3"

var (
	file_api_notes_v1_errors_proto_rawDescOnce sync.Once
	file_api_notes_v1_errors_proto_rawDescData []byte
)

func file_api_notes_v1_errors_proto_rawDescGZIP() []byte {
	file_api_notes_v1_errors_proto_rawDescOnce.Do(func() {
		file_api_notes_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notes_v1_errors_proto_rawDesc), len(file_api_notes_v1_errors_proto_rawDesc)))
	})
	return file_api_notes_v1_errors_proto_rawDescData
}

var file_api_notes_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_notes_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_notes_v1_errors_proto_goTypes = []any{
	(ErrorCode)(0),      // 0: api.notes.v1.ErrorCode
	(*CustomError)(nil), // 1: api.notes.v1.CustomError
}
var file_api_notes_v1_errors_proto_depIdxs = []int32{
	0, // 0: api.notes.v1.CustomError.code:type_name -> api.notes.v1.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_notes_v1_errors_proto_init() }
func file_api_notes_v1_errors_proto_init() {
	if File_api_notes_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_errors_proto_rawDesc), len(file_api_notes_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notes_v1_errors_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_errors_proto_depIdxs,
		EnumInfos:         file_api_notes_v1_errors_proto_enumTypes,
		MessageInfos:      file_api_notes_v1_errors_proto_msgTypes,
	}.Build()
	File_api_notes_v1_errors_proto = out.File
	file_api_notes_v1_errors_proto_goTypes = nil
	file_api_notes_v1_errors_proto_depIdxs = nil
}
