// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/notes/v1/notes.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoteAPI_CreateOrUpdateNote_FullMethodName = "/api.notes.v1.NoteAPI/CreateOrUpdateNote"
	NoteAPI_GetNote_FullMethodName            = "/api.notes.v1.NoteAPI/GetNote"
	NoteAPI_ListNotes_FullMethodName          = "/api.notes.v1.NoteAPI/ListNotes"
	NoteAPI_DeleteNote_FullMethodName         = "/api.notes.v1.NoteAPI/DeleteNote"
)

// NoteAPIClient is the client API for NoteAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteAPIClient interface {
	CreateOrUpdateNote(ctx context.Context, in *CreateOrUpdateNoteRequest, opts ...grpc.CallOption) (*CreateOrUpdateNoteResponse, error)
	GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error)
	ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error)
	DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error)
}

type noteAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteAPIClient(cc grpc.ClientConnInterface) NoteAPIClient {
	return &noteAPIClient{cc}
}

func (c *noteAPIClient) CreateOrUpdateNote(ctx context.Context, in *CreateOrUpdateNoteRequest, opts ...grpc.CallOption) (*CreateOrUpdateNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrUpdateNoteResponse)
	err := c.cc.Invoke(ctx, NoteAPI_CreateOrUpdateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) GetNote(ctx context.Context, in *GetNoteRequest, opts ...grpc.CallOption) (*GetNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNoteResponse)
	err := c.cc.Invoke(ctx, NoteAPI_GetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) ListNotes(ctx context.Context, in *ListNotesRequest, opts ...grpc.CallOption) (*ListNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotesResponse)
	err := c.cc.Invoke(ctx, NoteAPI_ListNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) DeleteNote(ctx context.Context, in *DeleteNoteRequest, opts ...grpc.CallOption) (*DeleteNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNoteResponse)
	err := c.cc.Invoke(ctx, NoteAPI_DeleteNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteAPIServer is the server API for NoteAPI service.
// All implementations should embed UnimplementedNoteAPIServer
// for forward compatibility.
type NoteAPIServer interface {
	CreateOrUpdateNote(context.Context, *CreateOrUpdateNoteRequest) (*CreateOrUpdateNoteResponse, error)
	GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error)
	ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error)
	DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error)
}

// UnimplementedNoteAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoteAPIServer struct{}

func (UnimplementedNoteAPIServer) CreateOrUpdateNote(context.Context, *CreateOrUpdateNoteRequest) (*CreateOrUpdateNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrUpdateNote not implemented")
}
func (UnimplementedNoteAPIServer) GetNote(context.Context, *GetNoteRequest) (*GetNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedNoteAPIServer) ListNotes(context.Context, *ListNotesRequest) (*ListNotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotes not implemented")
}
func (UnimplementedNoteAPIServer) DeleteNote(context.Context, *DeleteNoteRequest) (*DeleteNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNote not implemented")
}
func (UnimplementedNoteAPIServer) testEmbeddedByValue() {}

// UnsafeNoteAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteAPIServer will
// result in compilation errors.
type UnsafeNoteAPIServer interface {
	mustEmbedUnimplementedNoteAPIServer()
}

func RegisterNoteAPIServer(s grpc.ServiceRegistrar, srv NoteAPIServer) {
	// If the following call panics, it indicates UnimplementedNoteAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoteAPI_ServiceDesc, srv)
}

func _NoteAPI_CreateOrUpdateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).CreateOrUpdateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_CreateOrUpdateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).CreateOrUpdateNote(ctx, req.(*CreateOrUpdateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetNote(ctx, req.(*GetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_ListNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).ListNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_ListNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).ListNotes(ctx, req.(*ListNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_DeleteNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).DeleteNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_DeleteNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).DeleteNote(ctx, req.(*DeleteNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteAPI_ServiceDesc is the grpc.ServiceDesc for NoteAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notes.v1.NoteAPI",
	HandlerType: (*NoteAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrUpdateNote",
			Handler:    _NoteAPI_CreateOrUpdateNote_Handler,
		},
		{
			MethodName: "GetNote",
			Handler:    _NoteAPI_GetNote_Handler,
		},
		{
			MethodName: "ListNotes",
			Handler:    _NoteAPI_ListNotes_Handler,
		},
		{
			MethodName: "DeleteNote",
			Handler:    _NoteAPI_DeleteNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/notes/v1/notes.proto",
}
