// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/notes/v1/notes.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_notes_v1_notes_proto protoreflect.FileDescriptor

const file_api_notes_v1_notes_proto_rawDesc = "" +
	"\n" +
	"\x18api/notes/v1/notes.proto\x12\fapi.notes.v1\x1a\x1bapi/notes/v1/messages.proto2\xe1\x02\n" +
	"\aNoteAPI\x12i\n" +
	"\x12CreateOrUpdateNote\x12'.api.notes.v1.CreateOrUpdateNoteRequest\x1a(.api.notes.v1.CreateOrUpdateNoteResponse\"\x00\x12H\n" +
	"\aGetNote\x12\x1c.api.notes.v1.GetNoteRequest\x1a\x1d.api.notes.v1.GetNoteResponse\"\x00\x12N\n" +
	"\tListNotes\x12\x1e.api.notes.v1.ListNotesRequest\x1a\x1f.api.notes.v1.ListNotesResponse\"\x00\x12Q\n" +
	"\n" +
	"DeleteNote\x12\x1f.api.notes.v1.DeleteNoteRequest\x1a .api.notes.v1.DeleteNoteResponse\"\x00B2Z0github.com/Egorpalan/grpc-easyp/pkg/api/notes/v1b\x06proto3"

var file_api_notes_v1_notes_proto_goTypes = []any{
	(*CreateOrUpdateNoteRequest)(nil),  // 0: api.notes.v1.CreateOrUpdateNoteRequest
	(*GetNoteRequest)(nil),             // 1: api.notes.v1.GetNoteRequest
	(*ListNotesRequest)(nil),           // 2: api.notes.v1.ListNotesRequest
	(*DeleteNoteRequest)(nil),          // 3: api.notes.v1.DeleteNoteRequest
	(*CreateOrUpdateNoteResponse)(nil), // 4: api.notes.v1.CreateOrUpdateNoteResponse
	(*GetNoteResponse)(nil),            // 5: api.notes.v1.GetNoteResponse
	(*ListNotesResponse)(nil),          // 6: api.notes.v1.ListNotesResponse
	(*DeleteNoteResponse)(nil),         // 7: api.notes.v1.DeleteNoteResponse
}
var file_api_notes_v1_notes_proto_depIdxs = []int32{
	0, // 0: api.notes.v1.NoteAPI.CreateOrUpdateNote:input_type -> api.notes.v1.CreateOrUpdateNoteRequest
	1, // 1: api.notes.v1.NoteAPI.GetNote:input_type -> api.notes.v1.GetNoteRequest
	2, // 2: api.notes.v1.NoteAPI.ListNotes:input_type -> api.notes.v1.ListNotesRequest
	3, // 3: api.notes.v1.NoteAPI.DeleteNote:input_type -> api.notes.v1.DeleteNoteRequest
	4, // 4: api.notes.v1.NoteAPI.CreateOrUpdateNote:output_type -> api.notes.v1.CreateOrUpdateNoteResponse
	5, // 5: api.notes.v1.NoteAPI.GetNote:output_type -> api.notes.v1.GetNoteResponse
	6, // 6: api.notes.v1.NoteAPI.ListNotes:output_type -> api.notes.v1.ListNotesResponse
	7, // 7: api.notes.v1.NoteAPI.DeleteNote:output_type -> api.notes.v1.DeleteNoteResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_notes_v1_notes_proto_init() }
func file_api_notes_v1_notes_proto_init() {
	if File_api_notes_v1_notes_proto != nil {
		return
	}
	file_api_notes_v1_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notes_v1_notes_proto_rawDesc), len(file_api_notes_v1_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_notes_v1_notes_proto_goTypes,
		DependencyIndexes: file_api_notes_v1_notes_proto_depIdxs,
	}.Build()
	File_api_notes_v1_notes_proto = out.File
	file_api_notes_v1_notes_proto_goTypes = nil
	file_api_notes_v1_notes_proto_depIdxs = nil
}
